### ISSUE TITLE
Compiler error 

### ISSUE THREAD

**Issue by ik4u** [Zerbinati/Sugar_Galaxy#106]

**Comment by Galaxy-Wizard** [comment]
@ik4u to get latest C++ code from https://github.com/Galaxy-Wizard/Galaxy_Master/commit/56fee26ebe27fca8f709442fd239b3144274e70c

and try to compile.

**Comment by Galaxy-Wizard** [comment]
@ik4u to use ming 7.2.0 to compile.

**Comment by Galaxy-Wizard** [comment]
@ik4u I have got on https://github.com/Galaxy-Wizard/Galaxy_Master/commit/56fee26ebe27fca8f709442fd239b3144274e70c
success building.

1>------ Build started: Project: Sugar, Configuration: Debug x64 ------
1>benchmark.cpp
1>bitbase.cpp
1>bitboard.cpp
1>book.cpp
1>endgame.cpp
1>evaluate.cpp
1>main.cpp
1>material.cpp
1>misc.cpp
1>movegen.cpp
1>movepick.cpp
1>pawns.cpp
1>position.cpp
1>psqt.cpp
1>search.cpp
1>tbprobe.cpp
1>thread.cpp
1>timeman.cpp
1>tt.cpp
1>uci.cpp
1>Generating Code...
1>Compiling...
1>ucioption.cpp
1>Generating Code...
1>Sugar.vcxproj -> C:\Galaxy\Решения\Galaxy-master\source\x64\Debug\Sugar.exe
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
